import { useState, useEffect, useCallback } from "react";

export type Language = "fr" | "en" | "es" | "ar" | "pt";

export const translations = {
  fr: {
    // Profile
    profile: "Profil",
    manageSettings: "Gérez vos paramètres",
    user: "Utilisateur",
    activeAccount: "Compte actif",
    settings: "Paramètres",
    notifications: "Notifications",
    darkMode: "Mode sombre",
    privacy: "Confidentialité",
    helpSupport: "Aide & Support",
    language: "Langue",
    logout: "Déconnexion",
    appVersion: "MedReminder v1.0",
    healthPriority: "Votre santé, notre priorité 💚",
    // Dashboard
    hello: "Bonjour",
    yourHealth: "Votre santé",
    todayMeds: "médicaments aujourd'hui",
    progress: "Progression",
    morning: "Matin",
    afternoon: "Midi",
    evening: "Soir",
    night: "Nuit",
    noMeds: "Aucun médicament",
    addFirst: "Appuyez sur + pour ajouter un médicament",
    onOf: "sur",
    medications: "médicaments",
    allDone: "🎉 Bravo ! Tous vos médicaments sont pris",
    keepGoing: "💪 Continuez comme ça !",
    dontForget: "⏰ N'oubliez pas vos médicaments",
    healthTip: "Prenez vos médicaments à heure fixe",
    // Medication
    addMedication: "Ajouter un médicament",
    editMedication: "Modifier le médicament",
    medicationName: "Nom du médicament",
    name: "Nom",
    dosage: "Dosage",
    time: "Heure",
    intakeTime: "Heure de prise",
    save: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    edit: "Modifier",
    taken: "Pris",
    color: "Couleur",
    notes: "Notes (optionnel)",
    addMedicationBtn: "💊 Ajouter le médicament",
    saveChanges: "✅ Enregistrer les modifications",
    exampleName: "Ex: Doliprane",
    exampleDosage: "Ex: 500mg - 1 comprimé",
    exampleNotes: "Ex: À prendre avec de l'eau",
    frequency: "Fréquence",
    frequencyDaily: "Quotidien",
    frequencyWeekly: "Hebdomadaire",
    frequencyMonthly: "Mensuel",
    frequencyAsNeeded: "Si besoin",
    selectDays: "Sélectionner les jours",
    selectDates: "Sélectionner les dates du mois",
    monday: "Lun",
    tuesday: "Mar",
    wednesday: "Mer",
    thursday: "Jeu",
    friday: "Ven",
    saturday: "Sam",
    sunday: "Dim",
    // History
    history: "Historique",
    weeklyOverview: "Cette semaine",
    trackingIntakes: "Suivi de vos prises",
    completionRate: "Taux de complétion",
    takenToday: "Pris aujourd'hui",
    pending: "En attente",
    todayActivity: "Activité du jour",
    // All medications
    allMedications: "Tous les médicaments",
    myMedications: "Mes médicaments",
    medicationsRegistered: "médicament(s) enregistré(s)",
    search: "Rechercher un médicament...",
    all: "Tous",
    toTake: "À prendre",
    noResult: "Aucun résultat",
    // Nav
    home: "Accueil",
    medicationsNav: "Médicaments",
    // Alerts
    timeToTake: "Il est l'heure de prendre",
    takenAction: "Pris ✓",
    // Notification buttons
    remind: "Rappeler",
    view: "Voir",
    // Time periods
    medication: "médicament",
    medicationsPlural: "médicaments",
    noMedicationsForDate: "Aucun médicament enregistré pour cette date",
    loading: "Chargement...",
  },
  pt: {
    profile: "Perfil",
    manageSettings: "Gerenciar configurações",
    user: "Usuário",
    activeAccount: "Conta ativa",
    settings: "Configurações",
    notifications: "Notificações",
    darkMode: "Modo escuro",
    privacy: "Privacidade",
    helpSupport: "Ajuda e suporte",
    language: "Idioma",
    logout: "Sair",
    appVersion: "MedReminder v1.0",
    healthPriority: "Sua saúde, nossa prioridade 💚",
    hello: "Olá",
    yourHealth: "Sua saúde",
    todayMeds: "medicamentos hoje",
    progress: "Progresso",
    morning: "Manhã",
    afternoon: "Tarde",
    evening: "Noite",
    night: "Madrugada",
    noMeds: "Sem medicamentos",
    addFirst: "Toque em + para adicionar um medicamento",
    onOf: "de",
    medications: "medicamentos",
    allDone: "🎉 Parabéns! Todos os medicamentos foram tomados",
    keepGoing: "💪 Continue assim!",
    dontForget: "⏰ Não se esqueça de seus medicamentos",
    healthTip: "Tome seus medicamentos no horário",
    addMedication: "Adicionar medicamento",
    editMedication: "Editar medicamento",
    medicationName: "Nome do medicamento",
    name: "Nome",
    dosage: "Dosagem",
    time: "Hora",
    intakeTime: "Horário de ingestão",
    save: "Salvar",
    cancel: "Cancelar",
    delete: "Excluir",
    edit: "Editar",
    taken: "Tomado",
    color: "Cor",
    notes: "Notas (opcional)",
    addMedicationBtn: "💊 Adicionar medicamento",
    saveChanges: "✅ Salvar alterações",
    exampleName: "Ex: Paracetamol",
    exampleDosage: "Ex: 500mg - 1 comprimido",
    exampleNotes: "Ex: Tomar com água",
    frequency: "Frequência",
    frequencyDaily: "Diário",
    frequencyWeekly: "Semanal",
    frequencyMonthly: "Mensal",
    frequencyAsNeeded: "Conforme necessário",
    selectDays: "Selecionar dias",
    selectDates: "Selecionar datas do mês",
    monday: "Seg",
    tuesday: "Ter",
    wednesday: "Qua",
    thursday: "Qui",
    friday: "Sex",
    saturday: "Sáb",
    sunday: "Dom",
    history: "Histórico",
    weeklyOverview: "Esta semana",
    trackingIntakes: "Acompanhamento de suas ingestões",
    completionRate: "Taxa de conclusão",
    takenToday: "Tomados hoje",
    pending: "Pendente",
    todayActivity: "Atividade de hoje",
    allMedications: "Todos os medicamentos",
    myMedications: "Meus medicamentos",
    medicationsRegistered: "medicamento(s) registrado(s)",
    search: "Pesquisar medicamento...",
    all: "Todos",
    toTake: "Para tomar",
    noResult: "Nenhum resultado",
    home: "Início",
    medicationsNav: "Medicamentos",
    timeToTake: "Hora de tomar",
    takenAction: "Tomado ✓",
    remind: "Lembrar",
    view: "Ver",
    medication: "medicamento",
    medicationsPlural: "medicamentos",
    noMedicationsForDate: "Nenhum medicamento registrado para esta data",
    loading: "Carregando...",
  },
  en: {
    profile: "Profile",
    manageSettings: "Manage your settings",
    user: "User",
    activeAccount: "Active account",
    settings: "Settings",
    notifications: "Notifications",
    darkMode: "Dark mode",
    privacy: "Privacy",
    helpSupport: "Help & Support",
    language: "Language",
    logout: "Logout",
    appVersion: "MedReminder v1.0",
    healthPriority: "Your health, our priority 💚",
    hello: "Hello",
    yourHealth: "Your health",
    todayMeds: "medications today",
    progress: "Progress",
    morning: "Morning",
    afternoon: "Noon",
    evening: "Evening",
    night: "Night",
    noMeds: "No medications",
    addFirst: "Tap + to add a medication",
    onOf: "of",
    medications: "medications",
    allDone: "🎉 Well done! All medications taken",
    keepGoing: "💪 Keep it up!",
    dontForget: "⏰ Don't forget your medications",
    healthTip: "Take your medications on time",
    addMedication: "Add medication",
    editMedication: "Edit medication",
    medicationName: "Medication name",
    name: "Name",
    dosage: "Dosage",
    time: "Time",
    intakeTime: "Intake time",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    taken: "Taken",
    color: "Color",
    notes: "Notes (optional)",
    addMedicationBtn: "💊 Add medication",
    saveChanges: "✅ Save changes",
    exampleName: "E.g.: Tylenol",
    exampleDosage: "E.g.: 500mg - 1 tablet",
    exampleNotes: "E.g.: Take with water",
    frequency: "Frequency",
    frequencyDaily: "Daily",
    frequencyWeekly: "Weekly",
    frequencyMonthly: "Monthly",
    frequencyAsNeeded: "As needed",
    selectDays: "Select days",
    selectDates: "Select dates of the month",
    monday: "Mon",
    tuesday: "Tue",
    wednesday: "Wed",
    thursday: "Thu",
    friday: "Fri",
    saturday: "Sat",
    sunday: "Sun",
    history: "History",
    weeklyOverview: "This week",
    trackingIntakes: "Tracking your intakes",
    completionRate: "Completion rate",
    takenToday: "Taken today",
    pending: "Pending",
    todayActivity: "Today's activity",
    allMedications: "All medications",
    myMedications: "My medications",
    medicationsRegistered: "medication(s) registered",
    search: "Search medication...",
    all: "All",
    toTake: "To take",
    noResult: "No results",
    home: "Home",
    medicationsNav: "Medications",
    timeToTake: "Time to take",
    takenAction: "Taken ✓",
    // Notification buttons
    remind: "Remind",
    view: "View",
    medication: "medication",
    medicationsPlural: "medications",
    noMedicationsForDate: "No medications recorded for this date",
    loading: "Loading...",
  },
  es: {
    profile: "Perfil",
    manageSettings: "Gestiona tu configuración",
    user: "Usuario",
    activeAccount: "Cuenta activa",
    settings: "Configuración",
    notifications: "Notificaciones",
    darkMode: "Modo oscuro",
    privacy: "Privacidad",
    helpSupport: "Ayuda y Soporte",
    language: "Idioma",
    logout: "Cerrar sesión",
    appVersion: "MedReminder v1.0",
    healthPriority: "Tu salud, nuestra prioridad 💚",
    hello: "Hola",
    yourHealth: "Tu salud",
    todayMeds: "medicamentos hoy",
    progress: "Progreso",
    morning: "Mañana",
    afternoon: "Mediodía",
    evening: "Tarde",
    night: "Noche",
    noMeds: "Sin medicamentos",
    addFirst: "Toca + para añadir un medicamento",
    onOf: "de",
    medications: "medicamentos",
    allDone: "🎉 ¡Bien hecho! Todos los medicamentos tomados",
    keepGoing: "💪 ¡Sigue así!",
    dontForget: "⏰ No olvides tus medicamentos",
    healthTip: "Toma tus medicamentos a tiempo",
    addMedication: "Añadir medicamento",
    editMedication: "Editar medicamento",
    medicationName: "Nombre del medicamento",
    name: "Nombre",
    dosage: "Dosis",
    time: "Hora",
    intakeTime: "Hora de toma",
    save: "Guardar",
    cancel: "Cancelar",
    delete: "Eliminar",
    edit: "Editar",
    taken: "Tomado",
    color: "Color",
    notes: "Notas (opcional)",
    addMedicationBtn: "💊 Añadir medicamento",
    saveChanges: "✅ Guardar cambios",
    exampleName: "Ej: Ibuprofeno",
    exampleDosage: "Ej: 500mg - 1 comprimido",
    exampleNotes: "Ej: Tomar con agua",
    frequency: "Frecuencia",
    frequencyDaily: "Diario",
    frequencyWeekly: "Semanal",
    frequencyMonthly: "Mensual",
    frequencyAsNeeded: "Si es necesario",
    selectDays: "Seleccionar días",
    selectDates: "Seleccionar fechas del mes",
    monday: "Lun",
    tuesday: "Mar",
    wednesday: "Mié",
    thursday: "Jue",
    friday: "Vie",
    saturday: "Sáb",
    sunday: "Dom",
    history: "Historial",
    weeklyOverview: "Esta semana",
    trackingIntakes: "Seguimiento de tomas",
    completionRate: "Tasa de cumplimiento",
    takenToday: "Tomados hoy",
    pending: "Pendientes",
    todayActivity: "Actividad del día",
    allMedications: "Todos los medicamentos",
    myMedications: "Mis medicamentos",
    medicationsRegistered: "medicamento(s) registrado(s)",
    search: "Buscar medicamento...",
    all: "Todos",
    toTake: "Por tomar",
    noResult: "Sin resultados",
    home: "Inicio",
    medicationsNav: "Medicamentos",
    timeToTake: "Hora de tomar",
    takenAction: "Tomado ✓",
    // Notification buttons
    remind: "Recordar",
    view: "Ver",
    medication: "medicamento",
    medicationsPlural: "medicamentos",
    noMedicationsForDate: "No hay medicamentos registrados para esta fecha",
    loading: "Cargando...",
  },
  ar: {
    profile: "الملف الشخصي",
    manageSettings: "إدارة الإعدادات",
    user: "المستخدم",
    activeAccount: "حساب نشط",
    settings: "الإعدادات",
    notifications: "الإشعارات",
    darkMode: "الوضع الداكن",
    privacy: "الخصوصية",
    helpSupport: "المساعدة والدعم",
    language: "اللغة",
    logout: "تسجيل الخروج",
    appVersion: "MedReminder v1.0",
    healthPriority: "صحتك أولويتنا 💚",
    hello: "مرحبا",
    yourHealth: "صحتك",
    todayMeds: "أدوية اليوم",
    progress: "التقدم",
    morning: "صباح",
    afternoon: "ظهر",
    evening: "مساء",
    night: "ليل",
    noMeds: "لا توجد أدوية",
    addFirst: "اضغط + لإضافة دواء",
    onOf: "من",
    medications: "أدوية",
    allDone: "🎉 أحسنت! تم تناول جميع الأدوية",
    keepGoing: "💪 استمر!",
    dontForget: "⏰ لا تنسَ أدويتك",
    healthTip: "تناول أدويتك في الوقت المحدد",
    addMedication: "إضافة دواء",
    editMedication: "تعديل الدواء",
    medicationName: "اسم الدواء",
    name: "الاسم",
    dosage: "الجرعة",
    time: "الوقت",
    intakeTime: "وقت التناول",
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    edit: "تعديل",
    taken: "تم التناول",
    color: "اللون",
    notes: "ملاحظات (اختياري)",
    addMedicationBtn: "💊 إضافة الدواء",
    saveChanges: "✅ حفظ التغييرات",
    exampleName: "مثال: باراسيتامول",
    exampleDosage: "مثال: 500 مجم - قرص واحد",
    exampleNotes: "مثال: تناول مع الماء",
    frequency: "التكرار",
    frequencyDaily: "يومي",
    frequencyWeekly: "أسبوعي",
    frequencyMonthly: "شهري",
    frequencyAsNeeded: "عند الحاجة",
    selectDays: "اختر الأيام",
    selectDates: "اختر تواريخ الشهر",
    monday: "إثن",
    tuesday: "ثلا",
    wednesday: "أرب",
    thursday: "خمي",
    friday: "جمع",
    saturday: "سبت",
    sunday: "أحد",
    history: "السجل",
    weeklyOverview: "هذا الأسبوع",
    trackingIntakes: "تتبع جرعاتك",
    completionRate: "معدل الإكمال",
    takenToday: "تم اليوم",
    pending: "قيد الانتظار",
    todayActivity: "نشاط اليوم",
    allMedications: "جميع الأدوية",
    myMedications: "أدويتي",
    medicationsRegistered: "دواء مسجل",
    search: "البحث عن دواء...",
    all: "الكل",
    toTake: "للتناول",
    noResult: "لا توجد نتائج",
    home: "الرئيسية",
    medicationsNav: "الأدوية",
    timeToTake: "حان وقت تناول",
    takenAction: "تم ✓",
    // Notification buttons
    remind: "تذكير",
    view: "عرض",
    medication: "دواء",
    medicationsPlural: "أدوية",
    noMedicationsForDate: "لا توجد أدوية مسجلة لهذا التاريخ",
    loading: "جاري التحميل...",
  },
};

export const languageNames: Record<Language, string> = {
  fr: "Français",
  en: "English",
  es: "Español",
  ar: "العربية",
  pt: "Português",
};

export const useLanguage = () => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("app-language", language);
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
  }, [language]);

  const t = useCallback(
    (key: keyof typeof translations.fr): string => {
      return translations[language][key] || key;
    },
    [language]
  );

  return { language, setLanguage, t, languageNames };
};
